# Pre-commit configuration file.
# see https://pre-commit.com for more information
# see https://pre-commit.com/hooks.html for more hooks

repos:
  # Out of the box hooks for pre-commit
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-json
      - id: check-xml
      - id: check-case-conflict
      - id: check-docstring-first
      - id: debug-statements
      - id: check-added-large-files
        args: ["--maxkb=5000"]

  # Hook to sort import statements
  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.9.3
    hooks:
      - id: isort
        args:
          [
            "--multi-line=3",
            "--trailing-comma",
            "--force-grid-wrap=0",
            "--use-parentheses",
            "--line-width=79",
          ]

  # Hook to auto-format code to be compliant with PEP-8
  - repo: https://github.com/psf/black
    rev: 21.9b0
    hooks:
      - id: black
        args: [--line-length=79]

  # Hook to validate code style against PEP-8
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.2
    hooks:
      - id: flake8
        args: [--config=submodules/template-python/.flake8]
        additional_dependencies: [flake8-bugbear, flake8-docstrings]

  # Hook to validate code style against PEP-8
  - repo: https://github.com/pycqa/pylint
    rev: v2.12.2
    hooks:
      - id: pylint
        args: [--rcfile=submodules/template-python/.pylintrc]

  # Hook to validate static typing in the code
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.910-1
    hooks:
      - id: mypy
        args: [--config=submodules/template-python/mypy.ini]
        additional_dependencies: [types-PyYAML, types-requests]

  # Hook to auto-format non python files (i.a. md, yaml, xml, json)
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.4.1
    hooks:
      - id: prettier
        args: [--ignore-path=submodules/template-python/.prettierignore, --config=submodules/template-python/.prettierrc, --ignore-unknown]

  # Hook to automatically trigger all tests (it will pass also if no tests are found, i.e. exit code is 5)
  - repo: local
    hooks:
      - id: pytest
        name: pytest
        entry:
          sh -c 'python -m pytest -v; ret=$?; [ $ret = 5 ] && exit 0 || exit
          $ret'
        types: [python]
        verbose: true
        language: system
        pass_filenames: false
        stages: [commit]
